### ISSUE TITLE
I get build error and I'm new to Xcode

### ISSUE THREAD

**Issue by ishneor** [iabem97/saigon#10]
What do I do? Ive followed all the necessary steps but get a build error. the instructions tell me to change the bundle identifier to 'something unique along our team' which I dont understand. help?
________________________________________________________________________________________
Code Signing Error: There are no accounts registered with Xcode. Add your developer account to Xcode
Code Signing Error: No profiles for 'com.cheesecakeufo.saigon' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.cheesecakeufo.saigon'.
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'saigon/Info.plist'.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'

**Comment by gmardok** [comment]
You need to log in with your itunes development account. I use the same as for jailbrake 10.2 in cydia impactor

**Comment by ArtikusHG** [comment]
- Go to the project settings (Xcode right panel --> top file with blue icon named Saigon)

- Change com.cheesecakeufo.saigon to com.yourname.saigon

- Sign in to developer account (google this)

- Try sideloading again
