### ISSUE TITLE
ipad mini 4 rejailbreak problem...

### ISSUE THREAD

**Issue by skilo1** [iabem97/saigon#100]
I finally jailbroken my Ipad mini 4 on 10.2.1. but when I restarted I realized it was tethered, I had to go through that hell again trying to rejailbreak it and I keep getting "escaping sandbox error" or "privillage escalation error" and finally when It hits "Bypassing KPP" it resprings. 

to be honest I don't like spending 2 hours restarting my ipad and hitting the jailbreak button. It should not be difficult.

**Comment by mofarhand** [comment]
is there any update ?
