### ISSUE TITLE
iPhone 6s: OKcupid app causes reboot after jailbreak.

### ISSUE THREAD

**Issue by bmoffit** [iabem97/saigon#101]
I've repeated this experiment a few times.  Each time felt dramatic, as I had to go through the tireless task of jailbreaking again.

Steps:
* Jailbreak
* Open OKcupid app
** iPhone 6s reboots

This does not occur when the device is not jailbroken.  

I have crashreporter installed... but there's no logs showing this event.

**Comment by bmoffit** [comment]
Maybe this is intentional jailbreak detection/prevention.

**Comment by egamer24** [comment]
Are you able to install liberty and disable substrate etc for that app?

**Comment by bmoffit** [comment]
I'm guessing you mean the package from the [ryleyangus repo](https://ryleyangus.com/repo/).

I'll give it a shot.

**Comment by bmoffit** [comment]
Disabling substrate for that app, using liberty, still resulted in a reboot.
I'll try the jailbreak detection next, after I finally jailbreak again.

**Comment by bmoffit** [comment]
Liberty was not successful at stopping the reboot, even with jailbreak detection and disabling substrate for the okcupid app.

I suppose I'll just use the mobile web interface.

Can anyone else verify this behavior?  Or is this just happening to me?

**Comment by TaiTair** [comment]
Happens here as well - reboots unjailbroken. 
Not the only app causing this either. Keeping Liberty enabled does add stability though so I'm almost sure it has something to do with their jailbreak detection. It might detect the jailbreak and then bump the device back into the sandbox intentionally.

**Comment by bmoffit** [comment]
I obviously haven't provided enough info to help out here. 

Closing.
