### ISSUE TITLE
random tweak question.....................

### ISSUE THREAD

**Issue by skilo1** [iabem97/saigon#102]
is there such thing as a tweak that blocks apples anti kernel patching?

because jailbreak is getting more difficult and apple introduced kpp secutity. 

I just have to push this issue out even though questions are not allowed. but this is important, especially for the new Saigon jailbreak and that annoying reboot problem on "bypassing KPP".....

**Comment by ar0ck86** [comment]
There are post care of r/jailbreak that already cover this. This is not a support forum, instead it's for issues with the app or the jailbreak. Please google KPPless and close this issue skilo1.

**Comment by skilastic** [comment]
Thank you. I’m closing the issue
