### ISSUE TITLE
IP6S Rejailbreaking Reboot/Failed at privilege escalation

### ISSUE THREAD

**Issue by KoningHosselaar** [iabem97/saigon#104]
Goodmorning guys,

So yesterday I tried to jailbreak with Saigon and it litteraly took me a few hours to get Cydia on my phone and the jailbreak working.
So you know, I installed some tweaks and stuff and ofcourse with my badluck my phone froze and I had to hard reset.
While Cydia etc are still on my phone I tried to rejailbreak for a while now and it seems i'm ALWAYS rebooting at Privilege Escalation or that it says it failed at Privilege Escalation

**Comment by KoningHosselaar** [comment]
Nevermind. Got it to rejailbreak TWICE yesterday.

**Comment by feifeiwuxian** [comment]
ipad air 2 4G版也出现同样的情况。
