### ISSUE TITLE
Constant fail/reboot

### ISSUE THREAD

**Issue by wonkieinc** [iabem97/saigon#109]
I had success on first try and then my phone froze seconds later on the home screen (after respring) 

Tried re jail breaking since and It's failed every time and rebooted as I hit jailbreak

**Comment by shamaosaman** [comment]
worked on my 6sp n66ap device omg im so freaking happy rn and I been wait this for long damn time

**Comment by wonkieinc** [comment]
This was on my 6s n71mAP 10.2.1 

Still no success for me

**Comment by wonkieinc** [comment]
This eventually worked
