### ISSUE TITLE
./compile.sh doesn't work

### ISSUE THREAD

**Issue by ArtikusHG** [iabem97/saigon#11]
The ./compile.sh doesn't zip an iPA because of a small error in the code. Here's the right code for it to work (checked):

#!/bin/bash

echo "[*] Compiling Saïgon.."

$(which xcodebuild) clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -sdk xcrun -sdk iphoneos --show-sdk-path` -arch arm64

mv ./build/Release-iphoneos/Saigon.app ./

mkdir Payload

mv Saigon.app Payload/Saigon.app

echo "[*] Zipping into .ipa"

zip -r9 Saïgon.ipa ./Payload/Saigon.app

rm -rf build Payload

rm -rf Build

echo "[*] Done! Install .ipa with Impactor"

Hope this helps.

**Comment by Sem-Voigtlander** [comment]
Confirmed to reproduce this issue. Issue was fixed after changing it to your code. Thank you for your help. You should file a pull request.

**Comment by Koizum1** [comment]
#18
