### ISSUE TITLE
Boot loop issue

### ISSUE THREAD

**Issue by husaam2738** [iabem97/saigon#119]
Jailbreak works on iPhone 6s on 10.2.1 but stuck in a boot loop from a tweak don’t know how to get out

**Comment by PxLtommy** [comment]
hold power and home button for 6 secs, with volume down, then uninstall the tweak, then reboot as normal

**Comment by husaam2738** [comment]
Thanks will try it

**Comment by husaam2738** [comment]
Doesn’t seem to work device just reboots normally using beta 3 of Saigon

**Comment by andyvb1** [comment]
Click on the jailbreak button and hold down the volume down button if that doesnt work hold the volume up button.....

**Comment by husaam2738** [comment]
Ok will try
