### ISSUE TITLE
N53AP 5S CYDIA NOT SHOWING AFTER JAILBREAK

### ISSUE THREAD

**Issue by PxLtommy** [iabem97/saigon#123]
As the title says, I jailbreak with saigon B3 and it says you are already jailbroken, but cydia is not visible on the springboard. This is an error for everyone who is on N53AP saigon app. (on the 5S 10.2.1).
Please fix good sir <3 @iabem97

**Comment by andyvb1** [comment]
Search in spotlight if you have cydia if you dont it failed to install cydia idk why

**Comment by PxLtommy** [comment]
Nah it doesn't show, it seems like a common error for N53AP.

**Comment by PxLtommy** [comment]
**ALSO,** If I don't wait 1 minute after launching saigon app, and jailbreaking, it resprings with nothing. if I wait 1 min, then JB, it does the whole process successfully (and says i am jailbroken), but cydia DOES NOT show. It's like cydia installer package hasnt been installed or something. Also, it only says 'jailbreak failed, please reboot' about 1/10 tries. (I have tried everything. (holding volume, reboot, respring, re install)).
Hope that helps.
My conclusion: Something is bugged with N53AP on 5S.

**Comment by d0ppl3r** [comment]
Try to install Cydia over SSH.I have this error on my third iPhone 5s running iOS 10.2.1,but Cydia can be installed over Dropbear(SSH client)

**Comment by PxLtommy** [comment]
Could you give me steps? As I can't install openssh from cydia or anything, and trying to connect via filezilla gives me a rufuse error. @d0ppl3r

**Comment by th3nop** [comment]
Idk I have jailbroken with 5s and it works fine cydia installed right after jailbreak
