### ISSUE TITLE
Privilege escalation

### ISSUE THREAD

**Issue by ishneor** [iabem97/saigon#13]
Any clue as to the solution to this error? I'm on iPhone 7 10.2

**Comment by tmm08a** [comment]
Need the logs to know what error you're talking about. Use ghostbin or gist to post them please

**Comment by ishneor** [comment]
How do can i show u the logs? I'm new to Xcode and when I do to devices and simulators the logs I get are for like every moment the iPhone is running in the background, I dunno

**Comment by tmm08a** [comment]
In Xcode, there is an output window when running the application. Copy and paste that output.

**Comment by ishneor** [comment]
What output window? In the bottom after I activated the output console or in the devices and simulators section under 'window' up top?

**Comment by tmm08a** [comment]
In the bottom (assuming default xcode layout), not the one in the devices & simulators window. There's a comment on the reddit thread that has more detailed instructions on how to get the correct one showing in xcode.

**Comment by ishneor** [comment]
Nope couldnt find anything about that in the reddit thread. Could you tell me yourself the step-by-step procedure? I dont even know why nobody talks about this seemingly simple thing when I google this... why do i need to have frikin developer knowledge just to see some logs *sigh*

**Comment by jakeajames** [comment]
@ishneor On the top right you have three buttons, one closes/expandes the right panel, one for the bottom panel and one for the left panel. Click on the bottom one if it isn't expanded yet. All logs will appear on the bottom small window after clicking the Play button to run the app

**Comment by ishneor** [comment]
https://pastebin.com/fq9FfUH3

I got it. Apparently I just needed to hit the play/run button again with my iphone connected which reinstalls saigon just so you could see it running afterwards. weird if u ask me. but there you go the code is finally retrieved. i think the problem is the driver as mentioned on the reddit thread by OP...

**Comment by asduskun** [comment]
I have the same error with new IPA. I6s reboots when on privilege escalation. Why?

**Comment by xka1** [comment]
try to do so

1) install zJailbreak http://pangu8.com/jailbreak/10.2/
2) open
 install a beta ota blocker (tvOS beta software profile)
3) remove
zJailbreak
4) restart the device (power + home buton)
5) open saigon Beta 2r1
Option to reinstall Cydia by
holding 'jailbreak' button then tapping it again

**Comment by asduskun** [comment]
Is this reliable?
