### ISSUE TITLE
iPhone 6s iOS 10.2.1 - stopped re-jailbreaking 

### ISSUE THREAD

**Issue by TheWerdna338** [iabem97/saigon#134]
Initially, after rebooting my phone and using Saigon to re-jailbreak, it was working within 1-2 tries. However, as of late, after rebooting my phone and trying to re-jailbreak it's not happening even after 15+ tries.

**Comment by bzadoroz** [comment]
Try holding the volume up button while clicking jailbreak. Most likely you have a conflict with one of your installed tweaks

Sent from my iPhone

On Dec 13, 2017, 3:05 PM -0500, TheWerdna338 <notifications@github.com>, wrote:

Initially, after rebooting my phone and using Saigon to re-jailbreak, it was working within 1-2 tries. However, as of late, after rebooting my phone and trying to re-jailbreak it's not happening even after 15+ tries.

**Comment by TheWerdna338** [comment]
I have done this but am not sure if it is doing anything - the same problem still occurs for me just as if I wasn't holding the volume button.

**Comment by TheWerdna338** [comment]
After a few tries, I thought to hold down the jailbreak button, then it said 'tap again to reinstall cydia', I did this and it jailbroke again. However, all of my previously installed tweaks don't work anymore and even after reinstalling them they still don't work.

**Comment by fugiefire** [comment]
That happened to me as well, and it has happened to many others. I got it working again by just persistently clicking the jailbreak button until it worked
