### ISSUE TITLE
Not able to jailbreak iPhone 7 iOS 10.2.1

### ISSUE THREAD

**Issue by samashvin** [iabem97/saigon#138]
Shows error "Device Not Supported".

**Comment by Koff** [comment]
Maybe related to https://github.com/iabem97/saigon/issues/130

**Comment by samashvin** [comment]
So, whats the solution?

**Comment by Samgisaninja** [comment]
It’s not supported, the KPP bypass doesn’t work on A10 Fusion. This isn’t an issue, you’re trying to use it to jailbreak a device it was never designed to. 

Basically what you’re trying to do is fly to the moon in a propeller plane. It doesn’t work like that.

**Comment by samashvin** [comment]
Haha.. Thank for the clarification. I raised this issue cause some of tweeples were claiming they have jailbroken their iPhone 7 iOS 10.2.1! Anyway thanks a lot...
