### ISSUE TITLE
ipad Pro 9.7 (2016) "Not supported" [Fixed]

### ISSUE THREAD

**Issue by ChenNeffesh** [iabem97/saigon#148]
i have ipad Pro (2016) IOS 10.2.1  but its still show me "device not supported" with the beta3 

Will he support soon? or not? 

(sorry for my bad english)

**Comment by lastcc** [comment]
maybe you should download the compile with xcode

**Comment by inputfuture** [comment]
I saw on the author's Twitter that the author no longer maintains this project

**Comment by anaxci** [comment]
I started adding more offsets to the code
https://www.reddit.com/r/jailbreak/comments/7qug5d/release_sa%C3%AFgon_jailbreak_for_ipad_pro_1021/

**Comment by inputfuture** [comment]
@anaxci thank you!

**Comment by ChenNeffesh** [comment]
thanks. but its not working. Always reboots my device :(

i have iPad Pro 9.7 (2016 WIFI Only) Maybe it's not supported right now...

**Comment by ChenNeffesh** [comment]
@anaxci

**Comment by ChenNeffesh** [comment]
@anaxci Amazing! but its not working. always reboots my device and nothing :(

i have iPad Pro 9.7 (2016 WIFI Only) Maybe it's not yet supported On my device.

**Comment by anaxci** [comment]
Soft reset your device. (home+power) 
Try having some background load. (e.g.playing a spotify playlist) Open the app and wait for 30 sec. Press jailbreak
Start all over again if it fails

**Comment by ChenNeffesh** [comment]
@anaxci hi its working now but no cydia icon :(

its said "alredy jailbroken" but not cydia! please help.

**Comment by ChenNeffesh** [comment]
@anaxci  FIXED!! i just Press and hold the jailbreak Bottun for 10 seconds and jailbreak again. 
thank you so much! 
(sorry for my bad english)

**Comment by inputfuture** [comment]
@anaxci 

How do you use this data?I export these data here.(https://gist.github.com/uroboro/84309e91c1f92e873c943e94a00f3de1#gistcomment-2335006),But I do not know how to change the code,thank you!

```
iPad mini4 10.2.1 iPad5,2 A1550 J97AP

./find_offsets.sh iPad_64bit_TouchID_10.2.1_14D27_Restore.ipsw
[#] Downloading joker...
[#] Extracting...
[#] Done!
Darwin Kernel Version 16.3.0: Thu Dec 15 22:41:46 PST 2016; root:xnu-3789.42.2~1/RELEASE_ARM64_T7001

#define OFFSET_ZONE_MAP 0xfffffff007566360
#define OFFSET_KERNEL_MAP 0xfffffff0075c2058
#define OFFSET_KERNEL_TASK 0xfffffff0075c2050
#define OFFSET_REALHOST 0xfffffff007548a98
#define OFFSET_BZERO 0xfffffff00708e140
#define OFFSET_BCOPY 0xfffffff00708df80
#define OFFSET_COPYIN 0xfffffff00718f864
#define OFFSET_COPYOUT 0xfffffff00718fa6c
#define OFFSET_ROOTVNODE 0xfffffff0075c20b8
#define OFFSET_CHGPROCCNT 0xfffffff0073a4b64
#define OFFSET_KAUTH_CRED_REF 0xfffffff00737e8f8
#define OFFSET_IPC_PORT_ALLOC_SPECIAL 0xfffffff0070a6200
#define OFFSET_IPC_KOBJECT_SET 0xfffffff0070b98a0
#define OFFSET_IPC_PORT_MAKE_SEND 0xfffffff0070a5d44
#define OFFSET_IOSURFACEROOTUSERCLIENT_VTAB 0xfffffff006ed93e0
#define OFFSET_ROP_ADD_X0_X0_0x10 0xfffffff006471fb0
#define OFFSET_OSSERIALIZER_SERIALIZE 0xfffffff00745b324
#define OFFSET_ROP_LDR_X0_X0_0x10 0xfffffff0063c0ab8
```

**Comment by ChenNeffesh** [comment]
Closed. 

Thanks to @anaxci
