### ISSUE TITLE
Jailbreak failed at Escaping sandbox

### ISSUE THREAD

**Issue by Cloudftw** [iabem97/saigon#23]
Done on ipad mini 2
compiled using xcode then used cydia impactor to sign to device

**Comment by izhangxm** [comment]
Me too! iPhone 7 plus is also failed at  Escaping sandbox. Any one is successful at iPhone 7 Plus?

**Comment by tmm08a** [comment]
You will have to run triple fetch multiple times on each run, as it is a race condition. Closing as this isn't an issue.
