### ISSUE TITLE
iPhone 5S on iOS 10.2.1 failed to do the thing

### ISSUE THREAD

**Issue by RefractionGhoul** [iabem97/saigon#26]
As the title says, Saigon failed on my iPhone 5S on 10.2.1. I think it's a driver issue, but beats me. Any troubleshooting help would be appreciated. Log is in the Ghostbin below.
https://ghostbin.com/paste/wqede

**Comment by xevidos** [comment]
You can check your driver version with the tutorial below.

How to find your IDevice Driver Version:

Download Joker from http://newosxbook.com/tools/joker.html

Open your device's Settings->General->About
Scroll to Verison and find the number in brackets.
Use that version to search https://ipsw.me/ota and download your version. (It is normally the smaller file size one.)
Unzip that file
Go to AssetData/boot
Open a Terminal
Execute path/to/joker.universal -k path/to/kernelcache.release.*****

Search for something similar to 0xfffffff0060b26c0: H264 Video Encoder (com.apple.driver.AppleAVEH8)
If you are having trouble finding it would be easy to copy and paste the output of joker and then search for H264 Video Encoder

**Comment by pr1m0** [comment]
@xevidos Hey, I've done your tutorial ! / iPhone 6 OTA 10.2 to 10.2.1 
Ive found the offset

0xfffffff0061622c0: H264 Video Encoder (com.apple.driver.AppleAVEH7)

But for what how can I use that to work with Saigon? / you can catch up my Issue there are logs

**Comment by gmardok** [comment]
@pr1m0 Saigon doesn't work at all

**Comment by toniqyteza** [comment]
https://ghostbin.com/paste/okvkr
Same.
I hope the dev fixes it.

**Comment by iabem97** [comment]
@RefractionGhoul There seems to be an issue somewhere in the `apple_ave_utils_prepare_to_encode_frames` method. I'm working on debugging it.

@xevidos That'd be to find the literal driver kext to disassemble it in IDA/Hopper. You can list all the services/drivers available in your device but uncommenting this line:
`printf("[INFO]: Service: %s\n", service_name);` in function: `apple_ave_utils_get_connection`

@toniqyteza in your logs, you can see line 774 and 775:
```
[INFO]: successfully created a global surface with id: 24
[ERROR]: got a surface id bigger than 9. Might fail.
```
Which means that the surface id you got won't work. There seems to be a check somewhere in the driver to make sure that the surface id isn't bigger than 9.
Solution: just run Saïgon again. You'll still probably get the same prepare to encode frames error though.

**Comment by RefractionGhoul** [comment]
I don't know if it helps, but I'm using a Hackintosh and Xcode 9.1 Beta

**Comment by toniqyteza** [comment]
@iabem97 I hope you fix this soon man. I can still try but I'm sure it will show the same error.
