### ISSUE TITLE
Privilege escalation  

### ISSUE THREAD

**Issue by batkin111** [iabem97/saigon#30]
tested on iphone 6 plus 10.3.1
https://pastebin.com/ktzpRBEX

and tested on iphone 6 10.2.1
https://pastebin.com/yRgaPXGV

takes 1 or 2 reboots to get out of sandbox, then its the privilege error for both.

**Comment by Cloudftw** [comment]
First link shows 10.3.1 device which obviously doesn't work

**Comment by tuguScript** [comment]
I've just tried on iphone 7 plus. same result

**Comment by xka1** [comment]
try to do so

1) install zJailbreak http://pangu8.com/jailbreak/10.2/
2) open
 install a beta ota blocker (tvOS beta software profile)
3) remove
zJailbreak
4) restart the device (power + home buton)
5) open saigon Beta 2r1
Option to reinstall Cydia by
holding 'jailbreak' button then tapping it again

**Comment by jigsaw294** [comment]
lol I would not trust this.

**Comment by feifeiwuxian** [comment]
Ipad Air2 Cellular. same result
[*] Welcome to Saigon
[INFO]: machine: iPad5,4
[INFO]: build: 14D27
[INFO]: version: 10.2.1
[INFO]: sysname: Darwin
[INFO]: nodename: iPad
[INFO]: release: 16.3.0
[INFO]: kernel version: Darwin Kernel Version 16.3.0: Thu Dec 15 22:41:46 PST 2016; root:xnu-3789.42.2~1/RELEASE_ARM64_T7001
[INFO]: machine: iPad5,4
[INFO]: Detected RELEASE_ARM64_T7001
