### ISSUE TITLE
could this be causing the error?

### ISSUE THREAD

**Issue by techano** [iabem97/saigon#37]
[INFO]: successfully created surface
[INFO]: successfully created a global surface with id: 45 // creates it and set it to 45
[ERROR]: got a surface id bigger than 9. Might fail. // says it might fail if bigger then 9 
[INFO]: apple_ave_utils_prepare_to_encode_frames preparing to encode frames for connection
[ERROR]: Prepare to encode frame (error code: E00002BC)
[ERROR]: apple_ave_pwn_get_surface_kernel_address preparing to encode frames...
[ERROR]: apple_ave_pwn_init getting kernel pointer for surface 45
[ERROR]: initializing AppleAVE/VXE380 pwn
[ERROR]: initializing IOKit connections!

**Comment by iabem97** [comment]
You need to run Saigon again. Sometimes you get a surface id that's bigger than 9.
If you always get a surface that's over 9, then something's wrong.
I'll close this issue for now..
