### ISSUE TITLE
A litte step to fix it (I think)

### ISSUE THREAD

**Issue by MLGRadish** [iabem97/saigon#39]
Replaced the apple_ave_pwn.m with the original ziVA one + fixed it up and i got this log: https://pastebin.com/mYGjdx6V (I think this is an improvement).

And i belive there is a typo in apple_ave_pwn_get_surface_kernel_address
*(unsigned int*)((char*)g_bad_surface_buffer + OFFSET(encode_frame_offset_info_type)) = 0xffff; 
should be 
*(unsigned int*)((char*)g_bad_surface_buffer + OFFSET(encode_frame_offset_info_type)) = 0x4567;

But I'm not 100% sure, but I hope this helps.

**Comment by tehNinth** [comment]
Why not submit a pull request?

**Comment by amasriSF** [comment]
@MLGRadish looking at the logs you provided, it looks like the method is _still_ failing. I've already changed the value back to 0x4567.
Not sure what's causing the error since I do not have your console logs.
Can you please check the console logs from the Console app in your mac then send them here?

**Comment by iabem97** [comment]
@MLGRadish looking at the logs you provided, it looks like the method is still failing. I've already changed the value back to 0x4567.
Not sure what's causing the error since I do not have your console logs.
Can you please check the console logs from the Console app in your mac then send them here?

**Comment by MLGRadish** [comment]
How do I do that?

**Comment by iabem97** [comment]
Console app in Mac (it comes with macOS) then choose your device from the sidebar.
Run Saïgon then hit jailbreak.
You'll see a bunch of logs. Copy the whole thing (Cmd+A, Cmd+C) then upload it to Gist or Ghostbin.

**Comment by MLGRadish** [comment]
Ok I will do it when I get home.

**Comment by MLGRadish** [comment]
https://gist.github.com/anonymous/d80700e6d00bffe753389622230b7e4c here is the console + xcode log
The only difference from the first one is that at end the device panicked

**Comment by iabem97** [comment]
thank you. closing for now..
