### ISSUE TITLE
iPhone 6s 10.3.1 error with the latest update

### ISSUE THREAD

**Issue by dickie1** [iabem97/saigon#42]
https://gist.github.com/dickie1/5b73efc29d6e4dfa0081a26808c304bc

**Comment by dickie1** [comment]
https://gist.github.com/dickie1/74f74ec63f068d29cfa03de37368c34c
A second error at which the phone rebooted,first time happening

**Comment by iabem97** [comment]
Hmm.. prepare encode frames is still returning a general error (kIOReturnError 0x2bc). Can you get the logs through the console? (Search Console app in your mac) then choose your device from the sidebar.
Copy the entire log and put it in gist.

**Comment by khoahuynh47** [comment]
The 6s 10.3.1 while running Saigon jailbreak console log.
https://gist.github.com/khoahuynh47/9001e273a8f91af8569ab9aa6f1b6446

**Comment by dickie1** [comment]
https://gist.github.com/dickie1/a44c686d6539e5fe6ed05c5b957c6903 Console debug
https://gist.github.com/dickie1/67c58a4a943f491c96bd5ff3c9c60186 Xcode debug
