### ISSUE TITLE
IPhone 6 IOS: 10.2.1

### ISSUE THREAD

**Issue by ItzyCode** [iabem97/saigon#47]
Jailbreak failed at privilege escalation 
https://justpaste.it/1c6o3
Debug

do you will fix it?

**Comment by gmardok** [comment]
Is Master Yoda you?

**Comment by itjhin** [comment]
Encounter similar issue with iPad Air2 (wifi) on iOS 10.2.1

[log.txt](https://github.com/iabem97/saigon/files/1373360/log.txt)
