### ISSUE TITLE
Breaks at IOKit Initilizing

### ISSUE THREAD

**Issue by xevidos** [iabem97/saigon#5]
https://ghostbin.com/paste/j8ndb

Origional Error.

**Comment by iabem97** [comment]
try again. I've added detection for the AppleAVEDriver.
If you're still getting the same exact error, then you have a different driver.
Please submit logs through Ghostbin or Gist.

**Comment by xevidos** [comment]
The error is not exactly the same, however it is similar.

https://ghostbin.com/paste/3e4fm

For people who may not know, how can we tell what driver we have?  Also, how can we replace the driver to make it work with our devices?

**Comment by tmm08a** [comment]
@xevidos To determine the driver, run joker (-k flag IIRC) on your kernelcache file, which will get you a list of kexts. In that list, you should see a name similar to: 

`0xfffffff0060b26c0:` H264 Video Encoder `(com.apple.driver.AppleAVEH8)`

I'd recommend grepping the output from joker for "Video Encoder", and that should work

**Comment by xevidos** [comment]
I have the driver com.apple.driver.AppleAVEH8.  Do you have a tutorial on how to replace the driver in your code?

Also If anyone else has this question, I wrote up a short tutorial for you to give to them.

How to find your IDevice Driver Version:

Download Hopper from https://www.hopperapp.com/
Download Joker from http://newosxbook.com/tools/joker.html

Open your device's Settings->General->About
Scroll to Verison and find the number in brackets.
Use that version to search https://ipsw.me/ota and download your version. (It is normally the smaller file size one.)
Unzip that file
Go to AssetData/boot
Open a Terminal
Execute path/to/joker.universal -k path/to/kernelcache.release.*****

Search for something similar to 0xfffffff0060b26c0: H264 Video Encoder (com.apple.driver.AppleAVEH8)
If you are having trouble finding it would be easy to copy and paste the output of joker and then search for H264 Video Encoder

**Comment by gmardok** [comment]
So in my case the driver is AppleH7ADBE0. iPhone 6+ iOS 10.2.1
@xevidos any advise what to do next?

**Comment by xevidos** [comment]
I am looking through @iabem97 's code right now to see if I can find something.  However the easiest thing would be to wait until the developer releases his tutorial on how to swap out the drivers.  He mentioned he would in [this post on reddit](https://www.reddit.com/r/jailbreak/comments/74cxt7/releasesource_code_sa%C3%AFgon_a_potential_1021/).

"I will write a post on how to do this along with finding the methods/reverse engineer the drivers soon."

**Comment by gmardok** [comment]
Yeah, I saw that post. But its friday night, I'm not drunk and I have nothing to do :)

**Comment by xevidos** [comment]
This issue has been fixed in beta 2.

@gmardok are you having any more luck?
