### ISSUE TITLE
iPhone SE 64 GB

### ISSUE THREAD

**Issue by billcipherog** [iabem97/saigon#50]
Immidiate Kernel Panic at "escaping sandbox..." or at "patching amfid...".

Log: https://ghostbin.com/paste/fv632

**Comment by ruineka** [comment]
I also have an iPhone SE and it restarts immediately aftering "patching amfid..." Here is my ghostbin [https://ghostbin.com/paste/3p976](url)

**Comment by billcipherog** [comment]
https://ghostbin.com/paste/fv632
