### ISSUE TITLE
Sysctl handler wasn't installed

### ISSUE THREAD

**Issue by prmaciel** [iabem97/saigon#51]
[ERROR]: setting session settings
[ERROR]: using fake IOSurface... we should be dead by here.
[ERROR]: hw.l1dcachesize returned a normal size. seems like our sysctl handler wasn't installed.[ERROR]: reading kernel magic
[ERROR]: getting root

Any clues, guys?! Tks

**Comment by iabem97** [comment]
Please check other issues before posting. Duplicated
