### ISSUE TITLE
ipad mini 4 patching amfd error.....

### ISSUE THREAD

**Issue by skilo1** [iabem97/saigon#59]
hello, I have an ipad mini 4 on ios 10.2.1. but icant jailbreak it.  I press the button to jailbreak and I manage to get past (escaping sandbox). but I keep getting this error
_________________________________________
jailbreak failed on privilege escalation

tap the button below to reboot or hold 
the power + button for 6 seconds.

(REBOOT)

if your the owner please fix this issue............ and do not close this issue without fixing because its rude and it wouldn't be called an issue, it would be called a closed ticket!

**Comment by iabem97** [comment]
I don't think you looked through the other issues to create this one. **I am already aware of this issue** and I am working on a fix.
Closing because this is a duplicate.

**Comment by skilo1** [comment]
okay. I didn't know I was duplicating!
