### ISSUE TITLE
Can't sign saigon

### ISSUE THREAD

**Issue by IcyTower1337** [iabem97/saigon#60]
I've tried to sign saigon a couple of times now, but i've yet to succeed, first it asks me to change the team that builds it which i used my apple id, then i changed the build name.

Then I treid running it and it gives me this error, I've got no clue what I need to do.

https://puu.sh/xXkSg/6a413a8049.png

**Comment by s2339956** [comment]
try automatically mange signing ?

**Comment by IcyTower1337** [comment]
How would I do that? Sorry I'm new to xcode and don't really know how to do that...
