### ISSUE TITLE
iPhone 6s 10.2.1 Error

### ISSUE THREAD

**Issue by bmyhny** [iabem97/saigon#61]
Showing Recent Issues

Build target Saigon of project Saigon with configuration Debug

Check dependencies

Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'saigon/Info.plist'.

CompileC /Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/Objects-normal/x86_64/remote_call.o saigon/triple_fetch/remote_call.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/JakeyFlower/Desktop/saigon-master
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fmodules -gmodules -fmodules-cache-path=/Users/JakeyFlower/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/JakeyFlower/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mios-simulator-version-min=10.0 -g -Wno-sign-conversion -Winfinite-recursion -iquote /Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/Saigon-generated-files.hmap -I/Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/Saigon-own-target-headers.hmap -I/Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/Saigon-all-target-headers.hmap -iquote /Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/Saigon-project-headers.hmap -I/Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Products/Debug-iphonesimulator/include -I/Users/JakeyFlower/Desktop/saigon-master/Headers -I/Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/DerivedSources/x86_64 -I/Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/DerivedSources -F/Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/Objects-normal/x86_64/remote_call.d --serialize-diagnostics /Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/Objects-normal/x86_64/remote_call.dia -c /Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c -o /Users/JakeyFlower/Library/Developer/Xcode/DerivedData/Saigon-adhhdvunzfazjphgqjfzumpcfsuo/Build/Intermediates/Saigon.build/Debug-iphonesimulator/Saigon.build/Objects-normal/x86_64/remote_call.o

/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:50:3: error: use of undeclared identifier '_STRUCT_ARM_THREAD_STATE64'
  _STRUCT_ARM_THREAD_STATE64 thread_state = {0};
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:51:51: error: use of undeclared identifier 'thread_state'; did you mean 'thread_stateCnt'?
  mach_msg_type_number_t thread_stateCnt = sizeof(thread_state)/4;
                                                  ^~~~~~~~~~~~
                                                  thread_stateCnt
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:51:26: note: 'thread_stateCnt' declared here
  mach_msg_type_number_t thread_stateCnt = sizeof(thread_state)/4;
                         ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:54:3: error: use of undeclared identifier 'thread_state'
  thread_state.__sp = remote_stack_middle;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:55:3: error: use of undeclared identifier 'thread_state'
  thread_state.__pc = (uint64_t)_pthread_set_self;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:59:3: error: use of undeclared identifier 'thread_state'
  thread_state.__x[19] = loop_lr;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:60:3: error: use of undeclared identifier 'thread_state'
  thread_state.__lr = loop_lr;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:63:3: error: use of undeclared identifier 'thread_state'
  thread_state.__x[0] = 0;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:67:79: error: use of undeclared identifier 'thread_state'
  err = thread_create_running(task_port, ARM_THREAD_STATE64, (thread_state_t)&thread_state, thread_stateCnt, &thread_port);
                                                                              ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:67:42: error: use of undeclared identifier 'ARM_THREAD_STATE64'
  err = thread_create_running(task_port, ARM_THREAD_STATE64, (thread_state_t)&thread_state, thread_stateCnt, &thread_port);
                                         ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:77:78: error: use of undeclared identifier 'thread_state'
    err = thread_get_state(thread_port, ARM_THREAD_STATE64, (thread_state_t)&thread_state, &thread_stateCnt);
                                                                             ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:77:41: error: use of undeclared identifier 'ARM_THREAD_STATE64'
    err = thread_get_state(thread_port, ARM_THREAD_STATE64, (thread_state_t)&thread_state, &thread_stateCnt);
                                        ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:83:9: error: use of undeclared identifier 'thread_state'
    if (thread_state.__pc == loop_lr && thread_state.__x[19] == loop_lr){
        ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:83:41: error: use of undeclared identifier 'thread_state'
    if (thread_state.__pc == loop_lr && thread_state.__x[19] == loop_lr){
                                        ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:107:3: error: use of undeclared identifier 'thread_state'
  thread_state.__sp = remote_stack_middle;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:108:3: error: use of undeclared identifier 'thread_state'
  thread_state.__pc = (uint64_t)fptr;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:111:3: error: use of undeclared identifier 'thread_state'
  thread_state.__x[19] = loop_lr;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:112:3: error: use of undeclared identifier 'thread_state'
  thread_state.__lr = loop_lr;
  ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:130:9: error: use of undeclared identifier 'thread_state'
        thread_state.__x[i] = arg->value;
        ^
/Users/JakeyFlower/Desktop/saigon-master/saigon/triple_fetch/remote_call.c:139:9: error: use of undeclared identifier 'thread_state'
        thread_state.__x[i] = remote_buffer;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by bmyhny** [comment]
seems i was trying to compile saigon onto 6s simulator not my actual phone. got the saigon app on my device now just escaping sandbox as we speak all let you if i get past this screen

**Comment by bmyhny** [comment]
can't get past escaping sandbox sometimes i get past its and it says something then restrings but no cydia still trying

**Comment by bmyhny** [comment]
few more hours in expiring a new error [https://pastebin.com/LXD93SG5](url)

i feel like I'm getting closer yet further away

**Comment by xnuos** [comment]
@iy005: This is an **Issues** section. Not a _forum_. Your issue **does not change** unless the thread is generic on errors. **Please close this issue** as you have resolved your original issue However, secondly  be sure to **check** the _**other Issues**_ carefully to see if your error logs have a similar error to the ones mentioned. (As they do.) Then, please do _one_ of the two things below:

_**A.)** **If you find your issue:**_ 

**DO NOT POST IT OR SOMETHING LIKE THIS AGAIN!** I cannot stress the importance of this as it is part of the reason developers are driven from the public. It is irritating and only shows how little people regard the time of others. While this may be _your_ issue, it is the same for everyone else and posting this is not helpful, it just screams: 

> "I dont care to look at others peoples issues to see if there is something similar, I only care about **ME** and **MY** role in helping this work for **ME**."

 
That's not help, that's hindrance.

**_B.)_** **_If you do not find your issue:_**
Please post here as this is the **true purpose** of this section. Please title it according to the error received and provide logs from the debug. If he has the time or any information to provide you (or requires of you), he will let you know or ask, otherwise, you must patiently wait for a fix.

**Please close this Issue.**
