### ISSUE TITLE
Saigon app crashes on launch

### ISSUE THREAD

**Issue by Darkaim63** [iabem97/saigon#67]
I've sideloaded many apps before and I am aware of the procedures needed to get the app running, however, when the app is loaded onto my device it crashes on launch. Any solutions?

**Comment by AeroPwn** [comment]
check if the app certificate has been revoked 
Settings>General>Profiles & Device Management 
check to see if the app has been revoked this usually happens after 7 days of being side loaded

**Comment by Darkaim63** [comment]
Thank you for the quick response! I have just sideloaded the beta ipa today and I've revoked certificates in Cydia Impactor and everything.

**Comment by rnavalgund** [comment]
Happened to me too (iPad4,4 on 10.3.1) ik my model here is not supported, but if I run via Xcode, it runs perfectly fine to me.

**Comment by Darkaim63** [comment]
Same @rnavalgund with xCode is runs perfect but the app doesn't start at all on my iPhone 6 iOS 10.3.1

**Comment by rnavalgund** [comment]
@darkaim63 do you get anything past ioKit error?

**Comment by Darkaim63** [comment]
Sorry, I'm not so sure how to answer that, I kinda just started to get into xCode... @rnavalgund

**Comment by hcrrison** [comment]
Same happens here i6S 10.3.1

**Comment by xnuos** [comment]
@Darkaim63: This is an **Issues** section. If your specific issue in the title has been resolved and you can run the app, **please close this issue!** 

Also, you must realize **your device will do nothing** as there is no kernel patch protection bypass implemented (its literally in the title saying "iOS 10.2.1 Jailbreak," its not there for show btw) thus making even attempting to run this useless and infuriating to all other users. Please research your issues **before** you post them as they probably have already been answered.

Also:

@rnavalgund First be sure to **check** the _**other Issues**_ carefully to see if your error logs have a similar error to the ones mentioned. (As they do and supposedly have been fixed for supported devices.)
That way it eliminates the issue redundancy. 


**Please close this Issue.**

**Comment by rnavalgund** [comment]
@xnuos I agree with you. I thought this issue was closed. 

@Darkaim63 please close this issue.
