### ISSUE TITLE
iOS 10.3.1 KPPLess

### ISSUE THREAD

**Issue by Arwin1337** [iabem97/saigon#78]
Is KPPless by xerub works on 10.3.1,and will it help you for iOS 10.3.1 jailbreak creating?

**Comment by Arwin1337** [comment]
Is working*

**Comment by Arwin1337** [comment]
Please answer on this question,and I'll close it...

**Comment by ar0ck86** [comment]
This is not an issue with Saigon. You should close it anyway.
