### ISSUE TITLE
heres how to Fix to run on iPhone

### ISSUE THREAD

**Issue by T1V0h** [iabem97/saigon#8]
I figured it out. you have to use Xcode and in images.xcassets and then click on Appicon and remove all the photos and then you'll be able to compile It to you phone

**Comment by Morthin** [comment]
What did you fix? The compilation of the app to a device? Or successful run through JB process?

**Comment by gb160** [comment]
From reading some of the issues it seems there are major omissions/oversights for this to be a working jb,
