### ISSUE TITLE
iPhone 5s 10.2.1

### ISSUE THREAD

**Issue by zengqingf** [iabem97/saigon#84]

**Comment by toniqyteza** [comment]
son(?)

**Comment by gb160** [comment]
He commented recently that this device, and others (iPad Air) won't be supported as they use a different driver.

**Comment by RefractionGhoul** [comment]
Sorry to bump an older issue, but is it possible for us to manually add support? If so, how would one go about doing so?

**Comment by gb160** [comment]
God knows, the source hasn't been updated for ages and considering Cheesecakeufo's comments on this subject I presume getting any support for 5S/iPad Air is absolutely zero.
