### ISSUE TITLE
Infinite Reboot Loop

### ISSUE THREAD

**Issue by CounterSpikes** [iabem97/saigon#88]
Saigon finished doing its job (hooray) and I opened Cydia. Cydia wanted to reboot so I let it, but it's been rebooting for over 2 hours now. Not sure if this is considered one of the selfish requests but I haven't seen anyone else say anything similar yet. Would it be my device's problem or...?
![img_0043](https://user-images.githubusercontent.com/32977352/31849844-1c272784-b5fe-11e7-941d-ffb8e1002475.JPG)

**Comment by jochu38** [comment]
same here on  my ipad air 2


On 10/21/2017 2:21:44 AM, CounterSpikes <notifications@github.com> wrote:

Saigon finished doing its job (hooray) and I opened Cydia. Cydia wanted to reboot so I let it, but it's been rebooting for over 2 hours now. Not sure if this is considered one of the selfish requests but I haven't seen anyone else say anything similar yet. Would it be my device's problem or...?
[img_0043]<https://user-images.githubusercontent.com/32977352/31849844-1c272784-b5fe-11e7-941d-ffb8e1002475.JPG>

**Comment by CounterSpikes** [comment]
I see that it isn't just my problem anymore. Hopefully this isn't device specific haha

**Comment by CounterSpikes** [comment]
Note: I can guarantee that this is a loop because when unmuted, you charge the IPhone you can repeatedly hear the charger plug in noise go off constantly (every 5-10 seconds maybe?)
Note 2: This issue is also sort of related to issue #89. 
Thank you Saigon developer for even giving us the chance to jailbreak lol

**Comment by jigsaw294** [comment]
That is most likely Cydia fault. Mobile Substrate is probably not supported on 10.2.1 which in return crashes the device on low level which is why you keep hearing the charging noise when plugged in.

**Comment by jigsaw294** [comment]
All you can do is give it a bit of time or contact Saurik (Jay Freeman).

**Comment by sertik** [comment]
Any update at least is there a way to restore without upgrade?

**Comment by sertik** [comment]
hi?

**Comment by SOZIKILLYOUZ** [comment]
If you have t reset already, this was an error in the beta r1 where mobile substrate was enabled and should have been disabled (or the other way around, either way it wasn't supposed to be doing what it was doing) the only way to reset without uodating is via iCloud.com f your phone still connects to the internet

**Comment by sertik** [comment]
Thanks you for your reply
