### ISSUE TITLE
Stuck in bootloop i6s 10.2.1

### ISSUE THREAD

**Issue by sertik** [iabem97/saigon#89]
I have choose to install essential upgrade pop up at first cydia launch then im stuck in a bootloop

**Comment by CounterSpikes** [comment]
bump. Essentially that's what happened to a few of us too. Hopefully this issue gets resolved and I don't have to be forced to update my phone cuz iTunes refuses to let people restore em without updating :/

**Comment by sertik** [comment]
i dont think there is a fix all is probably corrupted i installed the essentials upgrade then the screen was black, i press power button then it bring me to lockscreen after unlock it the dock were gone i took it was a bug then i press home and power to reboot to get in bootloop

**Comment by sertik** [comment]
the only fix was if we were able to reset setting via impactor but no

**Comment by sertik** [comment]
i just need to know if there a hope otherelse i had no choice to upgrade?

**Comment by SOZIKILLYOUZ** [comment]
"You can reset via iCloud.com if the phone still connects to the internet"
