### ISSUE TITLE
Phone reboots on privilege escalation or patching amfid

### ISSUE THREAD

**Issue by xevidos** [iabem97/saigon#90]
On pressing jailbreak the following error is shown, the phone reboots or resprings (i am not sure whi one) and then I unlock the device and nothing happens.  I repeat the process and the exact same happens again.  Every once in a while it will not escape sandbox but when it does this happens.

I am on an iphone 6s+

https://pastebin.com/EtVvBANh

**Comment by xevidos** [comment]
This may be what it is supposed to do.  After trying over and over cydia finally installed.  I am not sure if it is supposed to auto re-boot the phone at failed privilege escalation though.  I am using beta 2 r1.

**Comment by MLGRadish** [comment]
Try the ipa the github version is out of date! Only the ipa works.

**Comment by xevidos** [comment]
I am using the IPA. The logs I got from the xcode version.  Either way the same thing happens

**Comment by xevidos** [comment]
I caught a glimpse of a message saying that if your phone reboots try again.  It just shows up very briefly.  This is what it's supposed to do.
