### ISSUE TITLE
BOOTLOOP ON BETA2r1

### ISSUE THREAD

**Issue by xXPaladinXx** [iabem97/saigon#92]
After installing sprigtomiz 4 my device went into a boot loop when I plug the charging cable in it keeps making the charging sound over and over again.

**Comment by Arwin1337** [comment]
Hard Reboot your Device.After this run the 'Saigon' app,tap on 'Jailbreak'.When your Device is respringing,tap and hold the 'Volume Up Down'.After this delete the 'Springtomize 4' from Cydia and respring your device.

**Comment by jigsaw294** [comment]
Watch out for the tweaks that are not compatible with ios 10.2.1 in the future (:

**Comment by Arwin1337** [comment]
Close the issue..

**Comment by xXPaladinXx** [comment]
it doesn’t turn on after a hard reboot.

**Comment by SOZIKILLYOUZ** [comment]
Reset via iCloud. Had the same problem and if it connects to the internet. Ths your only hope is to use iCloud.com to reset it
