### ISSUE TITLE
No video recording

### ISSUE THREAD

**Issue by prmaciel** [iabem97/saigon#93]
Hi guys, I sucesfully jailbreaked my IP6 (10.2.1) and installedusual tweaks (from ios 10 compatibility list) but I'm having issues with video recording. I can take pictures but during video recordings the phone only records audio and a white video... Just let me know if I can help sending any aditional info. Tks!

**Comment by Dry05** [comment]
This seems like an issue with the video/photo driver the jailbreak is based on. Contact the dev😉

**Comment by T1V0h** [comment]
weird a few times trying too use this jailbreak on my iph6 on 10.3.1 which not 10.2.1 my camera did the same and snapchat while trying to record a video it would stop right away. white screen with audio just like u. all I did was reboot my phone and it worked again

**Comment by prmaciel** [comment]
Tested again with Beta 2 and Camera is working properly! Tks
