### ISSUE TITLE
Source is not up to date

### ISSUE THREAD

**Issue by MLGRadish** [iabem97/saigon#94]
The current version of the source code does not up to date with the ipa, not even beta 1. Please update :(

**Comment by xevidos** [comment]
Someone on Reddit mentioned that there may be a couple bugs in the source that could potentially be harmful to people's devices if used incorrectly.  He specifically mentioned the offsets options.  I am not sure if this is true but it could be the reason he has not.  Be patient, he will release the source when it is ready.  I'm sure he will eventually update it.

**Comment by MLGRadish** [comment]
If someone is stupid enough to fuck it up, that's his problem.
