### ISSUE TITLE
ipad mini 4 resprings on "Bypassing KPP"

### ISSUE THREAD

**Issue by skilo1** [iabem97/saigon#96]
hello, I have an ipad mini 4 running on ios 10.2.1. I tested the  Saigon beta 2.ipa. but It restarts on "Bypassing KPP". even though it has not been tested, I was too excited. 

so can you fix this?
I hope I was first and not marked as duplicate again.....

**Comment by skilo1** [comment]
maybe fix in beta 3?

**Comment by SOZIKILLYOUZ** [comment]
Well, rebooting is the result of a kernel panic so the loo bypass obviously failed. I guess that the only thing you can do is wait for the beta 3 like you said and hope it gets fixed.

**Comment by skilo1** [comment]
thanks ;)

**Comment by skilo1** [comment]
also I doesn't reboot it resprings sorry.

**Comment by skilo1** [comment]
my made a mistake

**Comment by skilo1** [comment]
I finally jailbroken it, now I have to go though the errors of rejailbreaking it
